<a href="https://colab.research.google.com/github/hosngholami/Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Definiation 1 Demisional Array

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

Getting Size in Array

In [ ]:
a.shape

(7,)

In [ ]:
a[1]

np.int64(2)

Getting Element event in array

In [ ]:
a[::2]

array([1, 3, 5, 7])

In [69]:
b = np.array([
     [

        [100, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
      ],
      [
        [1000, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
      ],
      [
        [10000, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, -3],
        [5, 5, 5, 5, 5, -2],
        [6, 6, 6, 6, 6, -1],
      ]
])

In [70]:
for i in range(b.ndim):
  print(b[i].min(axis=1))


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[ 1  2  3 -3 -2 -1]


In [74]:
b.shape

(3, 6, 6)

In [75]:
n = [40, 40, 40, 40, 40, 40]
c = np.array([
    np.vstack((mat, n)) for mat in b
])



In [76]:
c.shape

(3, 7, 6)

In [79]:
# n = np.array([40, 40, 40, 40, 40, 40, 40])
n = np.full((7,1), 40)
print(c.shape)
d = np.array([
    np.hstack((mat, n)) for mat in c
])
print(d)

(3, 7, 6)
[[[  100     1     1     1     1     1    40]
  [    2     2     2     2     2     2    40]
  [    3     3     3     3     3     3    40]
  [    4     4     4     4     4     4    40]
  [    5     5     5     5     5     5    40]
  [    6     6     6     6     6     6    40]
  [   40    40    40    40    40    40    40]]

 [[ 1000     1     1     1     1     1    40]
  [    2     2     2     2     2     2    40]
  [    3     3     3     3     3     3    40]
  [    4     4     4     4     4     4    40]
  [    5     5     5     5     5     5    40]
  [    6     6     6     6     6     6    40]
  [   40    40    40    40    40    40    40]]

 [[10000     1     1     1     1     1    40]
  [    2     2     2     2     2     2    40]
  [    3     3     3     3     3     3    40]
  [    4     4     4     4     4    -3    40]
  [    5     5     5     5     5    -2    40]
  [    6     6     6     6     6    -1    40]
  [   40    40    40    40    40    40    40]]]


In [63]:
d

NameError: name 'd' is not defined

In [ ]:
np.where(b % 2 == 0, b, 0)

array([[[  100,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]],

       [[ 1000,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]],

       [[10000,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]]])

In [ ]:
b.shape

(3, 6, 6)

In [ ]:
l2 = np.array([
    [

        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ],
      [
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ],
      [
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ]

])

In [ ]:
l2.shape

(3, 2, 6)

In [ ]:
c = np.array([1, 2, 3, 4, 5])
d = np.array([6, 7, 8])

np.concatenate((c, d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
f = np.array([[1, 2], [3, 4]])
g = np.array([[5, 6]])

In [ ]:
z = np.concatenate((f, g), axis=0)
z
y2 = np.array([[5,6], [7,8]])
y3 = np.array([[10], [11], [12]])
z = np.concatenate((f, y2), axis=1)
z.shape
z
# np.concatenate((z, y3), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
z.shape

(2, 3)

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.sum(z, axis=0)

array([ 4,  6, 12, 14])

In [ ]:
np.sum(b, axis=0)

array([[11100,     3,     3,     3,     3,     3],
       [    6,     6,     6,     6,     6,     6],
       [    9,     9,     9,     9,     9,     9],
       [   12,    12,    12,    12,    12,    12],
       [   15,    15,    15,    15,    15,    15],
       [   18,    18,    18,    18,    18,    18]])

In [ ]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
print(b.shape)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [ ]:
x = a[np.newaxis, :]
p = x[np.newaxis, :]
y = p[:, np.newaxis]
print(p)
print(y)
print('**************')
print(x)
print(x.shape)
print(a.shape)
print(p.shape)
print(y.shape)
print('-------------------')


[[[0 1 2 3 4 5]]]
[[[[0 1 2 3 4 5]]]]
**************
[[0 1 2 3 4 5]]
(1, 6)
(6,)
(1, 1, 6)
(1, 1, 1, 6)
-------------------


In [ ]:
a = np.array([
    [
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
    ],

])
b = np.array([3, 3, 3, 3, 3, 3])
np.concatenate((a[0], b[np.newaxis, :]), axis=0)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3]])

In [ ]:
b = np.array([3, 3, 3, 3, 3, 3])
np.concatenate((a[0], b[:, np.newaxis]), axis=1)

array([[1, 1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 1, 1, 3]])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
upper = (a > 2)
print(a[upper])

[3 4 5 6]


In [ ]:
a = np.array([1,2,3,3,4,5,6,7,8,9,9])
b = np.unique(a, return_index=True)
b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 4, 5, 6, 7, 8, 9]))

In [ ]:
np.random.choice(np.arange(1, 10), size=(1, 5), replace=False)


array([[3, 9, 7, 8, 5]])