<a href="https://colab.research.google.com/github/hosngholami/Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Definiation 1 Demisional Array

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

Getting Size in Array

In [3]:
a.shape

(7,)

In [4]:
a[1]

np.int64(2)

Getting Element event in array

In [5]:
a[::2]

array([1, 3, 5, 7])

In [6]:
b = np.array([
     [

        [100, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
      ],
      [
        [1000, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
      ],
      [
        [10000, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
      ]


])

In [7]:
np.where(b % 2 == 0, b, 0)

array([[[  100,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]],

       [[ 1000,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]],

       [[10000,     0,     0,     0,     0,     0],
        [    2,     2,     2,     2,     2,     2],
        [    0,     0,     0,     0,     0,     0],
        [    4,     4,     4,     4,     4,     4],
        [    0,     0,     0,     0,     0,     0],
        [    6,     6,     6,     6,     6,     6]]])

In [8]:
b.shape

(3, 6, 6)

In [9]:
l2 = np.array([
    [

        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ],
      [
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ],
      [
        [1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],

      ]

])

In [10]:
l2.shape

(3, 2, 6)

In [14]:
c = np.array([1, 2, 3, 4, 5])
d = np.array([6, 7, 8])

np.concatenate((c, d))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
f = np.array([[1, 2], [3, 4]])
g = np.array([[5, 6]])

In [45]:
z = np.concatenate((f, g), axis=0)
z
y2 = np.array([[5,6], [7,8]])
y3 = np.array([[10], [11], [12]])
z = np.concatenate((f, y2), axis=1)
z.shape
z
# np.concatenate((z, y3), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
z.shape

(2, 3)

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.sum(z, axis=0)

array([ 4,  6, 12, 14])

In [48]:
np.sum(b, axis=0)

array([[11100,     3,     3,     3,     3,     3],
       [    6,     6,     6,     6,     6,     6],
       [    9,     9,     9,     9,     9,     9],
       [   12,    12,    12,    12,    12,    12],
       [   15,    15,    15,    15,    15,    15],
       [   18,    18,    18,    18,    18,    18]])